#!/bin/bash

BOOTING=false
if ! VBoxManage list runningvms | grep '"Docker"' > /dev/null; then
  echo -n 'Starting Docker VM'
  nohup VBoxHeadless -s Docker > /dev/null &
  BOOTING=true
fi 2> /dev/null
while :; do
  DOCKER_IP=$(VBoxManage guestproperty get Docker /VirtualBox/GuestInfo/Net/0/V4/IP 2>> /dev/null)
  if [ "$(echo "$DOCKER_IP" | awk '{ print $1 }')" == "Value:" ]; then
    DOCKER_IP=$(echo "$DOCKER_IP" | awk '{ print $2 }')
    break
  else
    echo -n '.'
    sleep 1
  fi
done
if $BOOTING; then
  # give it some time to fully start up
  for i in {1..5}; do
    echo -n '.'
    sleep 1
  done
  echo 'done'
fi

case "$1" in
"")
  if ! cat /etc/hosts | grep " docker" > /dev/null; then
    sudo bash -c "echo '$DOCKER_IP docker' >> /etc/hosts"
  else
    HOSTS_IP=$(sed -n 's/\(.*\) docker/\1/p' /etc/hosts)
    if [ "$DOCKER_IP" != "$HOSTS_IP" ]; then
      sudo bash -c "sed -i -E 's/.* docker/$DOCKER_IP docker/' /etc/hosts"
    fi
  fi
;;
-h)
  true
;;
*)
  echo $"Usage: $0 [-h]"
  echo $"-h skips updating the hosts file"
  exit 1
esac

ssh $DOCKER_IP
